# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5832263cb8338b97e2fc2bcd69319af92761c91889ca3e1aaf11bf4348c824ed57bb05546fc3304ca52689b88260b1d417f3b73ca038c6e710befa43a7a4dcdc

test:
  secret_key_base: 5bfd955bb8caa2c0a3019f35579532d44b877c55ae6879e6544b304144e683cc4c455a9da2bf763befa8c8f356f77273291d51668dda65627c2a3fd81d92fd9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
